Datos:
  Marca: Almagro
  Comuna: Las Condes
  NombreProyecto: Proyecto Prueba 8
  UrlProyecto: proyecto-prueba-8
  SitioPrincipal: https://socovesa.sharepoint.com/sites/PSP-EESS
  IdProyecto: 8
  ArchivoCSV: estructuraArquitectura_v4.csv
